/*
Purpose:
Calculate daily order volume.

Orders are grouped by date to identify demand trends
over time.
*/

select date(ordered_at), count(1)
from orders
group by 1
order by 1;

/*
The order_items table is joined to orders because
amount_paid represents the revenue generated by
each item purchased.
*/

select date(ordered_at), round(sum(amount_paid), 2)
from orders
    join order_items on orders.id = order_items.order_id
group by 1
order by 1;
