/*
Purpose:
Analyze revenue generated by a specific product.

This example focuses on the product 'kale-smoothie'
to understand its contribution over time.
*/

select date(ordered_at), round(sum(amount_paid), 2)
from orders
    join order_items on orders.id = order_items.order_id
where name = 'kale-smoothie'
group by 1
order by 1;
