/*
Purpose:
Analyze revenue generated by a specific product.

This example focuses on the product 'kale-smoothie'
to understand its contribution over time.
*/

select date(ordered_at), round(sum(amount_paid), 2)
from orders
    join order_items on orders.id = order_items.order_id
where name = 'kale-smoothie'
group by 1
order by 1;

/*
Revenue is aggregated by product name and sorted
from highest to lowest performer.
*/

select name, round(sum(amount_paid), 2)
from order_items
group by name
order by 2 desc;
